# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mify < Formula
  desc "Mify CLI - service infrastructure generator tool"
  homepage "https://mify.io/"
  version "0.1.17"
  license "Apache 2.0"

  on_macos do
    url "https://github.com/chebykinn/mify/releases/download/v0.1.17/mify-darwin-all.tar.gz"
    sha256 "2c730f950bf72f44f0315e89d582eeec8e8dabfeb0c9e1f5d8a1ee7c389f1cde"

    def install
      bin.install "mify"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chebykinn/mify/releases/download/v0.1.17/mify-linux-x86_64.tar.gz"
      sha256 "00b74b568eb113abe1c2f6f016ff98d92b664173c0b69ca59be6c6bd0378f8f7"

      def install
        bin.install "mify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chebykinn/mify/releases/download/v0.1.17/mify-linux-arm64.tar.gz"
      sha256 "f222cd4769ea5a31460a8394e0516239848ba8b62f345ee6f110ddf475f8bb9d"

      def install
        bin.install "mify"
      end
    end
  end
end
