# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mify < Formula
  desc "Mify CLI - service infrastructure generator tool"
  homepage "https://mify.io/"
  version "0.1.17"
  license "Apache 2.0"

  on_macos do
    url "https://github.com/chebykinn/mify/releases/download/v0.1.17/mify-darwin-all.tar.gz"
    sha256 "207ea8b6687633cf19ad6f0481410f3a7df1dde655d7734c22e0aa4cd3c90869"

    def install
      bin.install "mify"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chebykinn/mify/releases/download/v0.1.17/mify-linux-arm64.tar.gz"
      sha256 "032a8a3820aa07429ecb926af2aa04e175462b0b5434dfec127476a2f41141de"

      def install
        bin.install "mify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chebykinn/mify/releases/download/v0.1.17/mify-linux-x86_64.tar.gz"
      sha256 "88e31e87076c2807f61803a653d1a3f338d0747dafda960c59995fad59a95dde"

      def install
        bin.install "mify"
      end
    end
  end
end
