# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mify < Formula
  desc "Mify CLI - service infrastructure generator tool"
  homepage "https://mify.io/"
  version "0.1.18"
  license "Apache 2.0"

  on_macos do
    url "https://github.com/mify-io/mify/releases/download/v0.1.18/mify-darwin-all.tar.gz"
    sha256 "307d640f79962fa5490083c3f84e96fb45e6cee10b596f3f9096e00b3922cfe1"

    def install
      bin.install "mify"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mify-io/mify/releases/download/v0.1.18/mify-linux-arm64.tar.gz"
      sha256 "58df7b743334f867ad31891b0b100ab560594944a6c47aaa331d54fa23a6daac"

      def install
        bin.install "mify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mify-io/mify/releases/download/v0.1.18/mify-linux-x86_64.tar.gz"
      sha256 "d24555b83e125730f56719c5848f96686b4a5b15f9b3f32aedccf4e818d26f9b"

      def install
        bin.install "mify"
      end
    end
  end
end
